# .github/workflows/ci-caller.yml

# This workflow exists in all release branches and calls the actual CI workflow that lives in the
# ciworkflows branch. This enables us to manage the actual CI workflow in one place.
name: CI Caller

on:
  push:

permissions:
  contents: write
  pages: write
  id-token: write
  
concurrency:
  group: deploy-docs
  queue: max

jobs:
  ci:
    uses: augustmckendrick/queuetester/.github/workflows/shared-ci.yml@ciworkflows

  publish-to-pages:
    needs: ci
    if: needs.ci.outputs.skip != 'true'
    uses: augustmckendrick/queuetester/.github/workflows/deploy-pages.yml@ciworkflows