# .github/workflows/deploy-pages.yml
name: Deploy gh-pages to GitHub Pages

# This script replaces the automatic deployment of gh-pages Github normally does but
# we have turned it off to prevent conflicts.

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Set values so they can be used by the Github interface
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Here we are simply grabbing the gh-pages branch, creating an artifact to 
    # be deployed, and deploying that artifact.
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v6
        with:
          ref: gh-pages

      - name: Configure Pages
        uses: actions/configure-pages@v6

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5